services:
  - type: web
    name: igreja-backend
    env: node
    plan: free
    rootDir: ./backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health