services:
  # Backend service
  - type: web
    name: dizimos-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3333
    autoDeploy: true

  # Frontend web service
  - type: web
    name: dizimos-web
    env: node
    plan: free
    buildCommand: cd web && npm install && npm run build
    startCommand: cd web && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_API_URL
        value: https://dizimos-backend.onrender.com
    autoDeploy: true